[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = admin_dev_only
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
dev_mode = reload,qweb,werkzeug,xml
